email:
  from: "noreply@cider.uconn.edu"
  fake:
    enabled: true
    to: ["joseph.oshea@uconn.edu", "ronny.heredia@uconn.edu", "courtney.wiley@uconn.edu"]
    whitelist: []

hotjar:
  site_id: override-me

saml:
  idp_metadata: "vendor/engines/saml_authentication/spec/fixtures/idp_metadata.xml"
