apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nucore.fullname" . }}-auto-cancel
  labels:
    app: {{ include "nucore.name" . }}
    chart: {{ include "nucore.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "nucore.name" . }}
      release: {{ .Release.Name }}
      container: auto-cancel
  template:
    metadata:
      labels:
        app: {{ include "nucore.name" . }}
        release: {{ .Release.Name }}
        container: auto-cancel
    spec:
    {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
      {{- range . }}
        - name: {{ . }}
      {{- end }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./docker/auto_cancel.sh"]
          env:
            - name: MYSQL_HOST
              value: {{ .Values.mysql.host }}
            - name: MYSQL_PASS
              value: {{ .Values.mysql.pass }}
            - name: SETUP_HOST
              value: {{ include "nucore.fullname" . }}-setup
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
