apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nucore.fullname" . }}-setup
  labels:
    app: {{ include "nucore.name" . }}
    chart: {{ include "nucore.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "nucore.name" . }}
      release: {{ .Release.Name }}
      container: setup
  template:
    metadata:
      labels:
        app: {{ include "nucore.name" . }}
        release: {{ .Release.Name }}
        container: setup
    spec:
      volumes:
        - name: assets
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.assets.existingClaim | default (list (include "nucore.fullname" .) "assets" | join "-") }}
    {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
      {{- range . }}
        - name: {{ . }}
      {{- end }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./docker/migrate.sh"]
          env:
            - name: MYSQL_HOST
              value: {{ .Values.mysql.host }}
            - name: MYSQL_PASS
              value: {{ .Values.mysql.pass }}
          ports:
            - name: setup-talk
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: assets
              mountPath: /var/www/app/public/assets
# TODO: liveness/readiness probe setup-talk
#         livenessProbe:
#           httpGet:
#             path: /
#             port: http
#         readinessProbe:
#           httpGet:
#             path: /
#             port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
